name: rworkflows.devel
'on':
  push:
    branches: devel
  pull_request:
    branches: devel
jobs:
  rworkflows:
    permissions:
      contents: write
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    container: ${{ matrix.config.cont }}
    strategy:
      fail-fast: ${{ false }}
      matrix:
        config:
        - os: ubuntu-latest
          bioc: devel
          r: auto
          cont: bioconductor/bioconductor_docker:devel
          rspm: ~
        - os: macOS-latest
          bioc: devel
          r: auto
          cont: ~
          rspm: ~
        - os: windows-latest
          bioc: devel
          r: auto
          cont: ~
          rspm: ~
    steps:
    - uses: neurogenomics/rworkflows@master
      with:
        run_bioccheck: ${{ false }}
        run_rcmdcheck: ${{ true }}
        as_cran: ${{ true }}
        run_vignettes: ${{ true }}
        has_testthat: ${{ false }}
        run_covr: ${{ true }}
        run_pkgdown: ${{ true }}
        has_runit: ${{ true }}
        has_latex: ${{ false }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run_docker: ${{ false }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        runner_os: ${{ runner.os }}
        cache_version: cache-v1
        enable_act: ${{ false }}
